// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ddd

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AaaaaaClient is the client API for Aaaaaa service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AaaaaaClient interface {
	SayHello234(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type aaaaaaClient struct {
	cc grpc.ClientConnInterface
}

func NewAaaaaaClient(cc grpc.ClientConnInterface) AaaaaaClient {
	return &aaaaaaClient{cc}
}

func (c *aaaaaaClient) SayHello234(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/todo1.ddd.aaaaaa/SayHello234", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AaaaaaServer is the server API for Aaaaaa service.
// All implementations must embed UnimplementedAaaaaaServer
// for forward compatibility
type AaaaaaServer interface {
	SayHello234(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedAaaaaaServer()
}

// UnimplementedAaaaaaServer must be embedded to have forward compatible implementations.
type UnimplementedAaaaaaServer struct {
}

func (UnimplementedAaaaaaServer) SayHello234(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello234 not implemented")
}
func (UnimplementedAaaaaaServer) mustEmbedUnimplementedAaaaaaServer() {}

// UnsafeAaaaaaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AaaaaaServer will
// result in compilation errors.
type UnsafeAaaaaaServer interface {
	mustEmbedUnimplementedAaaaaaServer()
}

func RegisterAaaaaaServer(s grpc.ServiceRegistrar, srv AaaaaaServer) {
	s.RegisterService(&Aaaaaa_ServiceDesc, srv)
}

func _Aaaaaa_SayHello234_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AaaaaaServer).SayHello234(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo1.ddd.aaaaaa/SayHello234",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AaaaaaServer).SayHello234(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Aaaaaa_ServiceDesc is the grpc.ServiceDesc for Aaaaaa service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Aaaaaa_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "todo1.ddd.aaaaaa",
	HandlerType: (*AaaaaaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello234",
			Handler:    _Aaaaaa_SayHello234_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aaaaaa.proto",
}
