// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package fffff

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Ddd123Client is the client API for Ddd123 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Ddd123Client interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	TestFunc2(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type ddd123Client struct {
	cc grpc.ClientConnInterface
}

func NewDdd123Client(cc grpc.ClientConnInterface) Ddd123Client {
	return &ddd123Client{cc}
}

func (c *ddd123Client) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/fffff.fffff.ddd123/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ddd123Client) TestFunc2(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/fffff.fffff.ddd123/TestFunc2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Ddd123Server is the server API for Ddd123 service.
// All implementations must embed UnimplementedDdd123Server
// for forward compatibility
type Ddd123Server interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	TestFunc2(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedDdd123Server()
}

// UnimplementedDdd123Server must be embedded to have forward compatible implementations.
type UnimplementedDdd123Server struct {
}

func (UnimplementedDdd123Server) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedDdd123Server) TestFunc2(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestFunc2 not implemented")
}
func (UnimplementedDdd123Server) mustEmbedUnimplementedDdd123Server() {}

// UnsafeDdd123Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Ddd123Server will
// result in compilation errors.
type UnsafeDdd123Server interface {
	mustEmbedUnimplementedDdd123Server()
}

func RegisterDdd123Server(s grpc.ServiceRegistrar, srv Ddd123Server) {
	s.RegisterService(&Ddd123_ServiceDesc, srv)
}

func _Ddd123_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Ddd123Server).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fffff.fffff.ddd123/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Ddd123Server).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ddd123_TestFunc2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Ddd123Server).TestFunc2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fffff.fffff.ddd123/TestFunc2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Ddd123Server).TestFunc2(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ddd123_ServiceDesc is the grpc.ServiceDesc for Ddd123 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ddd123_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fffff.fffff.ddd123",
	HandlerType: (*Ddd123Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Ddd123_SayHello_Handler,
		},
		{
			MethodName: "TestFunc2",
			Handler:    _Ddd123_TestFunc2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ddd123.proto",
}
