// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ffff

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WwwwwClient is the client API for Wwwww service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WwwwwClient interface {
	Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type wwwwwClient struct {
	cc grpc.ClientConnInterface
}

func NewWwwwwClient(cc grpc.ClientConnInterface) WwwwwClient {
	return &wwwwwClient{cc}
}

func (c *wwwwwClient) Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/cccc.ffff.wwwww/Helloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WwwwwServer is the server API for Wwwww service.
// All implementations must embed UnimplementedWwwwwServer
// for forward compatibility
type WwwwwServer interface {
	Helloworld(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedWwwwwServer()
}

// UnimplementedWwwwwServer must be embedded to have forward compatible implementations.
type UnimplementedWwwwwServer struct {
}

func (UnimplementedWwwwwServer) Helloworld(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Helloworld not implemented")
}
func (UnimplementedWwwwwServer) mustEmbedUnimplementedWwwwwServer() {}

// UnsafeWwwwwServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WwwwwServer will
// result in compilation errors.
type UnsafeWwwwwServer interface {
	mustEmbedUnimplementedWwwwwServer()
}

func RegisterWwwwwServer(s grpc.ServiceRegistrar, srv WwwwwServer) {
	s.RegisterService(&Wwwww_ServiceDesc, srv)
}

func _Wwwww_Helloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WwwwwServer).Helloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cccc.ffff.wwwww/Helloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WwwwwServer).Helloworld(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Wwwww_ServiceDesc is the grpc.ServiceDesc for Wwwww service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Wwwww_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cccc.ffff.wwwww",
	HandlerType: (*WwwwwServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Helloworld",
			Handler:    _Wwwww_Helloworld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wwwww.proto",
}
